language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

php:
    - 5.6
    - 7.0
    - 7.1

matrix:
    fast_finish: true
    include:
        - php: 5.6
          env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest"

install:
    - travis_retry composer update ${COMPOSER_FLAGS} --prefer-dist --no-interaction

script:
    - composer test
